/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "all": {
        "clubs": {
            "search": string;
        };
        "game": {
            "recent": {
                "title": string;
            };
            "upcoming": {
                "title": string;
            };
        };
        "landing": {
            "description": string;
        };
        "partner": {
            "amount-of-games": string;
            "filters": {
                "all": string;
                "competition": string;
                "double": string;
                "games": string;
                "gameType": string;
                "linktype": string;
                "mix": string;
                "start-date": string;
                "tournament": string;
            };
            "name": string;
            "win-rate": string;
        };
        "players": {
            "my-club": string;
            "my-clubs": string;
            "my-profile": string;
            "search": string;
        };
        "points": {
            "needed-for-downgrade": string;
            "needed-for-upgrade": string;
            "table": {
                "level": string;
                "points-needed-down": string;
                "points-needed-up": string;
                "points-won": string;
            };
        };
        "settings": {
            "general": {
                "title": string;
            };
            "languages": {
                "en": string;
                "fr_BE": string;
                "nl_BE": string;
                "title": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
