export enum AlertType {
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  OVER_STOCK = 'OVER_STOCK',
  REORDER_NEEDED = 'REORDER_NEEDED',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  PRICE_CHANGE = 'PRICE_CHANGE',
  TEMPERATURE = 'TEMPERATURE',
  EQUIPMENT = 'EQUIPMENT',
}
