export enum NotificationType {
  LOW_STOCK = 'LOW_STOCK',
  ORDER_ALERT = 'ORDER_ALERT',
  EMPLOYEE_ALERT = 'EMPLOYEE_ALERT',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  REVENUE_MILESTONE = 'REVENUE_MILESTONE',
  REPORT_READY = 'REPORT_READY',
  INVENTORY_ALERT = 'INVENTORY_ALERT',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  QUALITY_ALERT = 'QUALITY_ALERT',
}
