export enum ScheduleConflictType {
  OVERTIME = 'OVERTIME',
  DOUBLE_BOOKING = 'DOUBLE_BOOKING',
  INSUFFICIENT_REST = 'INSUFFICIENT_REST',
  UNAVAILABLE_HOURS = 'UNAVAILABLE_HOURS',
  SKILL_MISMATCH = 'SKILL_MISMATCH'
}
